#!/usr/bin/env bash
set -euo pipefail

BATCH_SIZE=${BATCH_SIZE:-5}
BATCH_SEED=${BATCH_SEED:-123}
K_GAIN_JITTER=${K_GAIN_JITTER:-0.05}
DAMPING_JITTER=${DAMPING_JITTER:-0.05}
START_MARGIN=${START_MARGIN:-0.9}
TARGET_MARGIN=${TARGET_MARGIN:-0.9}
HISTORY_STRIDE=${HISTORY_STRIDE:-10}
POTENTIAL_STRIDE=${POTENTIAL_STRIDE:-10}
SAVE_POT_CSV=${SAVE_POT_CSV:-0}
POT_CSV_DIR=${POT_CSV_DIR:-pot_csv}
SHOW_PLOT=${SHOW_PLOT:-0}
SHOW_ANIMATION=${SHOW_ANIMATION:-0}

BATCH_SIZE=${BATCH_SIZE} \
BATCH_SEED=${BATCH_SEED} \
K_GAIN_JITTER=${K_GAIN_JITTER} \
DAMPING_JITTER=${DAMPING_JITTER} \
START_MARGIN=${START_MARGIN} \
TARGET_MARGIN=${TARGET_MARGIN} \
HISTORY_STRIDE=${HISTORY_STRIDE} \
POTENTIAL_STRIDE=${POTENTIAL_STRIDE} \
SAVE_POT_CSV=${SAVE_POT_CSV} \
POT_CSV_DIR=${POT_CSV_DIR} \
SHOW_PLOT=${SHOW_PLOT} \
SHOW_ANIMATION=${SHOW_ANIMATION} \
/home/kpapantoniou/MyProjects/Particle-Sim/particle_sim/bin/python test_core.py "$@"
